### ISSUE TITLE
Purpose of Certain Parameters?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [guanjue/IDEAS_2018#14]
Hello @guanjue,

I wanted to understand the purpose of certain parameters. 

1. `cap`
I just set this to the highest number in my dataset. 
That seems a bit strange to do though since there may be some important usage of this parameter I don't understand. 

2. `train`
Is it better or more accurate to set this at a higher number?
Obviously, I would expect increasing this to increase computational time. 

3. `trainsz`
What exactly are the units for it?
What does the default parameter value `500000` mean?

4. `norm`
Is there any situation you think it's best to use standardized values?
Any reason the default is not to standardize?

5. `smooth`
What does it mean to make "states more homogenous along the genome"?

6. `burnin`
Are higher numbers better overall?
I realize this will increase computational time.

**Comment by guanjue** [comment]
Hi, Yogindra

For these parameters:
1, "cap" is the upper threshold of the signal. The signal greater than the cap will be set as the cap signal. We usually set it to 16 because we converted our signal to -log10(p-value) based on local adjusted negative binomial model. So the cap equals to 16 corresponds to p-value = 1e-16.

2, More train number will output a more robust epigenetic state set.

3, The IDEAS randomly select some 500000*bin-size (default bin-size is 200bp) region to initialize the model.

4, Because we already normalized our data before running IDEAS, we usually not use the IDEAS's internal "norm". One thing to be cautious is that the scale function may inflate the noise of the sample with weaker signals.  

5, It means the signal is smooth along the genome so that a state transition between each  200bp bin along the genome will be less noisy. 

6, I only used the default value for this parameter before, and I did not evaluated what is the effects of change this parameter.

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
Thanks so much for this!
As always, I really do appreciate it. 

Is there any reason why `smooth` isn't set to `1` by default?

As well, is there any place that explains what the following output files mean?

- `*.cluster`
- `*.para`
- `*.profile`
- `*.state`

**Comment by YogiOnBioinformatics** [comment]
Hello @guanjue, 

Apologies, don't mean to bother. 
Just wanted to follow up on this. 🙂

**Comment by guanjue** [comment]
Sorry for the late reply. These are some descriptions about these output
files:

*.state: The Epigenetic states and position classes for the genome across
all input cell types. First 4 columns are index, chr, position_st
position_ed (position_ed will be the same as position_st if only one
position for each window is provided in input) The next X columns are
epigenetic states, where X=total number of cell types, including
replicates. The last column is the position class label in IDEAS local
clustering.

*.para: The first column in the Frequency of the state. The next N columns
are the sum and variance parameters for each epigenetic states.

*.cluster file: Local cell type clustering result, one row for each cell
type.

*.profile: This file can be ignored.


Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
Thanks so much for the reply! 
Here's my understanding of how things work. 

Once `IDEAS` is done running, I need to create the heatmap so I can understand what state number corresponds with which biological event. 
Is the above correct?

As well, I had a question about this: 
`The last column is the position class label in IDEAS local clustering.`

What exactly does that mean in lay mans terms?

**Comment by guanjue** [comment]
That column is show the cell-types clusters of each 200bp bin (it is try to cluster all 200bp bins into clusters based on the epigenetic profiles across multiple cell types. details can be found in the IDEAS-2016 paper). For the purpose of generating the epigenetic state tracks, this can be ignored.

**Comment by YogiOnBioinformatics** [comment]
Closing this issue.
