### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by Lila14** [guanjue/IDEAS_2018#5]
I'm trying to run IDEAS on some ENCODE data. It runs normally for a number of iterations. But then I get the following output: 

> [1] "ideas encode.input hg19_1kb_windows_filtered_sorted.bed -impute None -minerr 0.5 -cap 16 -sample 20 5 -otherpara /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.para0 /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.profile0 -G 15 -thread 32 -o /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.chr1 -inv      1000       0"
> 0: 0 x 5
> 5: 0 x 6
> 11: 0 x 6
> 17: 0 x 6
> 23: 0 x 5
> 28: 0 x 5
> N=6 Marks=6, Cov=0, Mean=0.000000, Sd=0.031623
> N=6, L=0, A=1.016667, K=1
> [6] itern0 : /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.chr1.script: line 10:  8214 Bus error               (core dumped) ideas encode.input hg19_1kb_windows_filtered_sorted.bed -impute None -minerr 0.5 -cap 16 -sample 20 5 -otherpara /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.para0 /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.profile0 -G 15 -thread 32 -o /home/lur159/git/IDEAS_2018/encode_data/encode_result/encode.chr1 -inv 1000 0
> Error in runideas(args, target[i], head, inv[i, -1]) : 
>   IDEAS quite unexpectedly
> Execution halted

I've attached my input files. (I had to change the extensions so that they'd upload, you can remove ".txt"). 
[encode.parafile.txt](https://github.com/guanjue/IDEAS_2018/files/2446631/encode.parafile.txt)
[encode.input.txt](https://github.com/guanjue/IDEAS_2018/files/2446632/encode.input.txt)
[run_encode.sh.txt](https://github.com/guanjue/IDEAS_2018/files/2446634/run_encode.sh.txt)

**Comment by yuzhang123** [comment]
Hi, the output says nothing is read from the input file ("L=0" means 
length of data per cell is 0), and it is likely because of '-inv 1000 0' 
at the last of your command line.

If this is what you manually input, please change it to something like 
"-inv 1000 2000" which means reading rows [1000,2000). If you used 
parafile, which generated this command line, then please check 
hg19_1kb_windows_filtered_sorted.bed.inv and see if it is written like

chr1 0 1000

chr2 1000 2104

...

Thanks,

Yu

**Comment by guanjue** [comment]
Can you also show the head of hg19_1kb_windows_filtered_sorted.bed
For the hg19_1kb_windows_filtered_sorted.bed file, the delimiter should be whitespace.

Guanjue

**Comment by Lila14** [comment]
Thanks for the quick reply. I've attached the heads of my interval files.

[hg19_1kb_windows_filtered_sorted.bed.inv.head.txt](https://github.com/guanjue/IDEAS_2018/files/2447445/hg19_1kb_windows_filtered_sorted.bed.inv.head.txt)
[hg19_1kb_windows_filtered_sorted.bed.head.txt](https://github.com/guanjue/IDEAS_2018/files/2447446/hg19_1kb_windows_filtered_sorted.bed.head.txt)

**Comment by yuzhang123** [comment]
The inv file is the problem. It is not about window positions in genome, 
it is about which sets of windows in .bed file are in one chromosome.

So if your bed file reads like

chr1 0 100

chr1 100 200

chr1 200 300

chr2 0 100

chr2 100 200

chr3 0 100

Then your inv file should be

chr1 0 3

chr2 3 5

chr3 5 6

Because inv file tells the program that lines [0,3) in bed are for chr1, 
and lines [3,5) in bed are for chr2 etc.

**Comment by yuzhang123** [comment]
By the way, it is perfectly fine to remove the split option in parafile, 
so you won't need inv file. It is only used so to speed up computation 
by running each chromosome in parallel

**Comment by guanjue** [comment]
Also, you need to replace the "tab" delimiter by "whitespace". After you replace it, the previous script should also work.
